# -*- coding: utf-8 -*-
"""Project3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oX4zH1cKuvXqRjzdvjaqTNfdgNnQceU4

**Title of Project**

Financial Market News Sentiment Analysis

**Objective**

FSA can be defined as a field of study that analyzes people's sentiment from financial texts, measures and quantifies investor sentiment from financial textual sentiment, and is finally grounded in the applications of market prediction and financial decision-making.

**Import Library**
"""

import pandas as pd

import numpy as np

"""**Import Data**"""

df = pd.read_csv('https://raw.githubusercontent.com/Lorddhaval/Dataset/main/Financial%20Market%20News.csv', encoding = "ISO-8859-1")

"""**Describe Data**"""

df.head()

df.info()

"""**Data Preprocessing**"""

df.shape

df.columns

' '.join(str(x) for x in df.iloc[1,2:27])

df.index

len(df.index)

news = []
for row in range(0,len(df.index)):
  news.append(''.join(str(x) for x in df.iloc[row,2:27]))

type(news)

news[0]

"""**Define Target Variable (y) and Feature Variables(X)**"""

X = news

type(X)

"""**Modelling**"""

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase = True, ngram_range=(1,1))

X = cv.fit_transform(X)

X.shape

y = df['Label']

y.shape

"""**Train Test Split**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, stratify = y, random_state=222529)

"""**Model Evaluation**"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)

rf.fit(X_train, y_train)

"""**Prediction**"""

y_pred = rf.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))

